[package]
name = "sha2_fixed_64"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpufeatures = "0.2"

[dev-dependencies]
digest = "0.10.5"
sha2 = "0.10.6"
